language: python
python:
- '3.5.2'
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database fast_food-DB;' -i -u akram
addons:
  postgresql: "9.4"
script:
  - pytest --cov=.
  - coverage  
  - coveralls 
after_success:
- coveralls

  

